### ISSUE TITLE
Context menu has a different geometry in v7

### ISSUE THREAD

**Issue by Mirmentrud** [icflorescu/mantine-contextmenu#117]
**Describe the bug**
The context menu seems to have a different behavior on v7. I am rendering the context menu via `ContextMenuPortal`, and while it was working nicely in v6, the behavior becomes weird in v7: the geometry becomes way off, going to the last element and not respecting the input position, and the width spreading through the window.

**To Reproduce**
I am rendering `ContextMenuPortal` using `react-laag`. 

**Expected behavior**
The behavior should stay like in v6.

**Screenshots**
v6:
![Screenshot from 2023-11-02 04-30-45](https://github.com/icflorescu/mantine-contextmenu/assets/131544382/f40d8dc9-88e5-46c9-b03f-4883fb3d09b1)

v7:
![Screenshot from 2023-11-02 04-36-15](https://github.com/icflorescu/mantine-contextmenu/assets/131544382/df1c7ff7-b10e-4766-b8b5-cc87c4a26230)

**Desktop (please complete the following information):**

- OS: Ubuntu 22
- Browser: Chrome, Firefox
- Version: 7.1.2

**Comment by icflorescu** [comment]
The internals of Mantine Context Menu have indeed changed lately, partly because [the entire styling behind Mantine V7](https://github.com/mantinedev/mantine/releases) have changed once they've migrated to native CSS, and partly as a necessity to implement [submenus](https://icflorescu.github.io/mantine-contextmenu/examples/submenus/). That's why the behavior can't *stay like in V6*.

Providing a working reproduction (on codesandbox or something similar) that I could test on, to check your particular usage scenario, would be a necessary first step in order to understand what's happening and how this affects you.

Thanks.

**Comment by icflorescu** [comment]
You forgot to import the CSS, see https://codesandbox.io/p/sandbox/crazy-galileo-6y5zmj?file=%2Fsrc%2Fmain.tsx%3A5%2C1-5%2C41.

I'd suggest you to read the styling guide for more details and quirks: https://icflorescu.github.io/mantine-contextmenu/styling/

**Comment by Mirmentrud** [comment]
Nice catch, thanks! It wasn't obvious to me that there's a new CSS file to be imported when upgrading to v7, maybe this is just my dyslexic tendency.
