### ISSUE TITLE
ContextMenuPortal: useClickOutside hook?

### ISSUE THREAD

**Issue by TheAlan404** [icflorescu/mantine-contextmenu#129]
**Is your feature request related to a problem? Please describe.**
the opening and closing of the context menu is janky

**Describe the solution you'd like**
use the [useClickOutside](https://mantine.dev/hooks/use-click-outside/) hook provided by mantine in [ContextMenuPortal](https://github.com/icflorescu/mantine-contextmenu/blob/main/package/ContextMenuPortal.tsx#L11) instead of the window events

maybe also add custom events/controlling of the behavior too?

**Comment by icflorescu** [comment]
What do you mean by "janky"?

The window events in [ContextMenuPortal.tsx](https://github.com/icflorescu/mantine-contextmenu/blob/main/package/ContextMenuPortal.tsx#L11) have nothing to do with [useClickOutside](https://mantine.dev/hooks/use-click-outside/). The `useClickOutside` hook simply does what its name implies, while the window event subscriptions you're referring to are there to ensure the menu is closed when the user presses `Escape` or the windows is resized (i.e. when a mobile device is rotated).

Initially I was using the `useClickOutside` hook to control the menu closing, but I had to walk away from it when I added the [submenus feature](https://icflorescu.github.io/mantine-contextmenu/examples/submenus/). If you're curious why, when implementing submenus, best practice says you need to apply a delay before closing a submenu, to give the user's pointer enough time to travel from the trigger to the submenu area.

So, to be honest, I don't really understand what's this about. Is this something you consider a bug (again, what do you mean by "janky") or...?

**Comment by icflorescu** [comment]
laconic < explicit < verbose 😀
In other words, there's a huge difference between laconic and verbose and I'd always go with "explicit".

Yes, I see what you mean now.

> In other contexts such as operating system apps for example, when you right click on somewhere else while a context menu is open, it closes the context menu then reopens one where you right clicked. Right now mantine-contextmenu treats right clicks outside the context menu the same way it does left clicks.

As a matter of fact, a few versions back I was relying on `useClickOutside` and the behavior was the one you describe. But @Songkeys came up with [this perfectly reasonable suggestion](https://github.com/icflorescu/mantine-contextmenu/issues/120) (and a PR), and I found the argument reasonable.

**Good catch on submenus not working on mobile**, I'll have a look and try to come up with a fix soon.

> why doesn't mantine-contextmenu use the Mantine [Menu](https://mantine.dev/core/menu/) component?

AFAIK, the Mantine [Menu](https://mantine.dev/core/menu/) component needs to create some DOM elements in order to implement its functionality, which wouldn't be acceptable in certain situations - such as when using a context-menu on table rows - see [Mantine DataTable](https://icflorescu.github.io/mantine-datatable/examples/using-with-mantine-contextmenu/) for an example.

**Comment by icflorescu** [comment]
Thanks for chiming in, @Songkeys. TBH, I think it's good enough as it is. It's the same behavior I'm seeing in my current browsers (Brave, Firefox and Edge), and in Manjaro Linux with KDE (don't have a mac or windows to test on at the moment).

When you have an open context-menu and right-click on something else, the currently open context menu closes, but you don't get a new one opening.

@TheAlan404 - I'll be coming up with a fix for the submenu bug on mobile in a few minutes, thanks again for noticing.

**Comment by icflorescu** [comment]
The bug with submenus not showing on mobile devices is fixed in `V7.3.1`.

Unrelated to this, I've noticed there is, however, a potential improvement to be made: at the moment, the corresponding submenu is shown when the user is hovering over the parent item, with a small (configurable) delay. However, I think we could instantly show the submenu without a delay if/when the user **clicks** on on the parent item...

Feel free to have a look if you have the time and the mood (I don't at the moment; it's 10:40 PM here and I'm going to call it a day :-).
